#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.config/nexus-cli"
CONFIG_FILE="$CONFIG_DIR/.env"
SKILLS_DIR="$CONFIG_DIR/skills"
WRAPPER="$BIN_DIR/nexus"

if ! python3 -c 'import requests' >/dev/null 2>&1; then
  echo "Dependency Python 'requests' belum ada."
  echo "Install dulu dengan salah satu command ini:"
  echo "  sudo apt install python3-requests"
  echo "  python3 -m pip install --user requests"
  exit 1
fi

mkdir -p "$BIN_DIR" "$CONFIG_DIR" "$SKILLS_DIR"

# Wrapper memakai PROJECT_DIR via env var, bukan path hardcoded.
# Ini agar wrapper tetap berfungsi walaupun install.sh dipindah atau
# repo di-clone ke lokasi berbeda.
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by nexus-cli installer. Do not edit; re-run install.sh.
export NEXUS_CLI_HOME="$PROJECT_DIR"
exec python3 -m nexus_cli --workspace "\$PWD" "\$@"
EOF
chmod +x "$WRAPPER"

if [ ! -f "$CONFIG_FILE" ]; then
  if [ -n "${NVIDIA_API_KEY:-}" ]; then
    printf 'NVIDIA_API_KEY=%s\n' "$NVIDIA_API_KEY" > "$CONFIG_FILE"
  else
    cp "$PROJECT_DIR/.env.example" "$CONFIG_FILE"
  fi
  chmod 600 "$CONFIG_FILE"
fi

if [ ! -f "$SKILLS_DIR/core.md" ]; then
  cat > "$SKILLS_DIR/core.md" <<'EOF'
# Core Agent

- Bekerja seperti coding agent terminal: baca konteks dulu, buat perubahan terarah, lalu verifikasi.
- Gunakan tool file untuk membaca dan mengedit file, jangan mengarang isi file.
- Setelah selesai, jelaskan singkat file yang diubah dan hasil verifikasi.
EOF
fi

if [ ! -f "$SKILLS_DIR/terminal.md" ]; then
  cat > "$SKILLS_DIR/terminal.md" <<'EOF'
# Terminal

- Gunakan `shell_command` untuk menjalankan command di workspace saat perlu inspeksi, build, test, atau menjalankan dev server.
- Mulai dari command ringan seperti `ls`, `rg`, `npm test`, `python3 -m compileall`, atau command proyek yang relevan.
- Jangan menjalankan command destruktif tanpa alasan kuat.
EOF
fi

if [ ! -f "$SKILLS_DIR/browser.md" ]; then
  cat > "$SKILLS_DIR/browser.md" <<'EOF'
# Browser

- Gunakan `open_browser` untuk membuka URL lokal seperti `http://localhost:3000` atau file HTML hasil kerja.
- Jika membuat website statis, buka file HTML setelah selesai bila user ingin melihat hasilnya.
- Jika membuat app dengan dev server, jalankan server melalui `shell_command` lalu buka URL-nya dengan `open_browser`.
EOF
fi

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    SHELL_RC="$HOME/.bashrc"
    if [ -n "${ZSH_VERSION:-}" ]; then
      SHELL_RC="$HOME/.zshrc"
    fi
    printf '\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$SHELL_RC"
    echo "PATH ditambahkan ke $SHELL_RC. Jalankan: source $SHELL_RC"
    ;;
esac

echo "Nexus siap dipakai."
echo "Command: nexus"
echo "Config API key: $CONFIG_FILE"
echo "Skills: $SKILLS_DIR"
echo "Contoh: cd /path/proyek && nexus"
